[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "net"
format = " $icon $signal_strength "
device = "^wl"
interval = 10

[[block]]
block = "net"
format = " $icon $ip "
device = "^en"

[[block]]
block = "sound"
format = " $icon $volume "
device = "pulse"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:1) "
format_alt = " $icon_swap $swap_used_percents.eng(w:1) "
interval = 10

[[block]]
block = "temperature"
interval = 5

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%m-%d %H:%M') "
